import { createSignal, For, Show, type JSX } from 'solid-js';
import { marked } from 'marked';
import type { Legend, Schema, EdgeSchema, NodeSchema } from './api';

interface LegendModalProps {
  legend: Legend;
  schemas: Record<string, Schema>;
  onClose: () => void;
}

function isEdge(s: Schema): s is EdgeSchema {
  return s.kind === 'edge';
}

function isNode(s: Schema): s is NodeSchema {
  return s.kind !== 'edge';
}

function NodeSchemaRow(props: { schema: NodeSchema }): JSX.Element {
  const s = props.schema;
  return (
    <tr class="border-t border-border-subtle group">
      <td class="px-3 py-2">
        <span class="group-hover:hidden">{s.label}</span>
        <span class="hidden group-hover:inline font-mono text-xs">{s.name}</span>
      </td>
      <td class="px-3 py-2 text-xs text-fg-muted">
        {s.legendDescription ?? ''}
        <Show when={s.accepts}>
          <span class={s.legendDescription ? ' ml-2' : ''}>accepts: {s.accepts!.join(', ')}</span>
        </Show>
      </td>
    </tr>
  );
}

function EdgeSchemaRow(props: { schema: EdgeSchema }): JSX.Element {
  const s = props.schema;
  return (
    <tr class="border-t border-border-subtle group">
      <td class="px-3 py-2">
        <span class="group-hover:hidden">{s.label}</span>
        <span class="hidden group-hover:inline font-mono text-xs">{s.name}</span>
      </td>
      <td class="px-3 py-2 text-xs text-fg-muted">
        {s.legendDescription ?? ''}
        <Show when={s.directed}><span class={s.legendDescription ? ' ml-2' : ''}>directed</span></Show>
        <Show when={s.layoutRole}><span class="ml-2">layout: {s.layoutRole}</span></Show>
        <Show when={s.style?.stroke}>
          <span class="ml-2 inline-flex items-center gap-1">
            <span class="inline-block w-3 h-3 rounded-sm" style={{ background: s.style!.stroke }} />
            {s.style!.stroke}
          </span>
        </Show>
      </td>
    </tr>
  );
}

const mdStyles = 'text-sm text-fg [&>h1]:text-xl [&>h1]:font-bold [&>h1]:mb-2 [&>h2]:text-lg [&>h2]:font-semibold [&>h2]:mb-2 [&>h3]:text-base [&>h3]:font-semibold [&>h3]:mb-1 [&>p]:mb-2 [&>p:last-child]:mb-0 [&>ul]:list-disc [&>ul]:pl-5 [&>ul]:mb-2 [&>ol]:list-decimal [&>ol]:pl-5 [&>ol]:mb-2 [&>li]:mb-1';

const ABOUT_CONTENT = `
# Luminous

Luminous bridges human visual thinking and AI structured context. Humans reason well with spatial canvas tools; AI performs well with high-quality structured context. Luminous is the interface between both.

## How it works

A **canvas** is a spatial document containing typed nodes and edges. Nodes represent domain concepts — components, signals, data sources — and edges represent relationships between them.

Canvases can be created in two ways:

- **Diagram pipelines** — scripts that read source code via static analysis and emit canvas files. The pipeline is the reusable artifact, shareable across projects and communities. Each pipeline defines its own node types from the forces of its domain.
- **MCP-assisted design** — using Luminous as an MCP server, you can collaborate with an AI agent to diagram product requirements, architecture, and system design on a spatial canvas. Once the design is right, hand the structured canvas data off to an AI coding agent to build it.

## This canvas

What you're viewing was generated by \`scripts/analyze-solidjs.ts\`, a pipeline that performs static analysis of the Luminous codebase itself. It extracts the Solid.js component tree, reactive signals, stores, effects, and the data flow edges between them.

The canvas is regenerated on every deployment — it always reflects the current state of the code.

## Learn more

- [GitHub repository](https://github.com/saxonthune/Luminous)
- Licensed under [AGPL-3.0](https://www.gnu.org/licenses/agpl-3.0.html)
`.trim();

export function LegendModal(props: LegendModalProps): JSX.Element {
  const [view, setView] = createSignal<'legend' | 'about'>('legend');

  const blurbHtml = () => marked.parse(props.legend.blurb, { async: false }) as string;
  const aboutHtml = () => marked.parse(ABOUT_CONTENT, { async: false }) as string;

  const nodeSchemas = () => Object.values(props.schemas).filter(isNode);
  const edgeSchemas = () => Object.values(props.schemas).filter(isEdge);

  return (
    <div
      class="fixed inset-0 z-[9999] flex items-center justify-center"
      style={{ "backdrop-filter": "blur(4px)", background: "rgba(0,0,0,0.3)" }}
      onClick={(e) => { if (e.target === e.currentTarget) props.onClose(); }}
    >
      <div
        class="rounded-lg border border-border bg-surface max-w-2xl w-full max-h-[80vh] flex flex-col"
        style={{ "box-shadow": "var(--shadow-lg)" }}
      >
        {/* Sticky header */}
        <div class="flex items-center justify-between px-6 pt-3 pb-2 mb-0 border-b border-border-subtle shrink-0">
          <div class="flex items-baseline mt-0 gap-3">
            <Show
              when={view() === 'legend'}
              fallback={
                <button
                  onClick={() => setView('legend')}
                  class="text-sm text-fg-muted hover:text-fg"
                >
                  &larr; Legend
                </button>
              }
            >
              <h2 class="text-2xl font-bold text-fg">Legend</h2>
              <button
                onClick={() => setView('about')}
                class="text-sm text-accent hover:underline"
              >
                What is Luminous?
              </button>
            </Show>
          </div>
          <button
            onClick={props.onClose}
            class="w-7 h-7 flex items-center justify-center rounded-md text-fg-muted hover:text-fg hover:bg-surface-alt"
          >
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
              <line x1="1" y1="1" x2="13" y2="13" />
              <line x1="13" y1="1" x2="1" y2="13" />
            </svg>
          </button>
        </div>

        {/* Scrollable body */}
        <div class="overflow-y-auto px-6 py-4">
          <Show when={view() === 'legend'}>
            {/* Blurb */}
            <div class={`${mdStyles} mb-6`} innerHTML={blurbHtml()} />

            {/* Node schemas */}
            <Show when={nodeSchemas().length > 0}>
              <h3 class="text-sm font-semibold text-fg mb-2">Node types</h3>
              <table class="w-full text-sm text-left text-fg mb-4">
                <thead>
                  <tr class="text-xs text-fg-muted uppercase">
                    <th class="px-3 py-1">Type</th>
                    <th class="px-3 py-1">Details</th>
                  </tr>
                </thead>
                <tbody>
                  <For each={nodeSchemas()}>
                    {(s) => <NodeSchemaRow schema={s as NodeSchema} />}
                  </For>
                </tbody>
              </table>
            </Show>

            {/* Edge schemas */}
            <Show when={edgeSchemas().length > 0}>
              <h3 class="text-sm font-semibold text-fg mb-2">Edge types</h3>
              <table class="w-full text-sm text-left text-fg mb-4">
                <thead>
                  <tr class="text-xs text-fg-muted uppercase">
                    <th class="px-3 py-1">Type</th>
                    <th class="px-3 py-1">Details</th>
                  </tr>
                </thead>
                <tbody>
                  <For each={edgeSchemas()}>
                    {(s) => <EdgeSchemaRow schema={s as EdgeSchema} />}
                  </For>
                </tbody>
              </table>
            </Show>
          </Show>

          <Show when={view() === 'about'}>
            <p class="text-xs italic text-fg-muted mb-4">This content is AI-generated. Apologies.</p>
            <div class={`${mdStyles} [&>a]:text-accent [&>a]:underline [&_a]:text-accent [&_a]:underline`} innerHTML={aboutHtml()} />
          </Show>
        </div>
      </div>
    </div>
  );
}
